### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by giacomocerquone** [marilari88/zod-playground#1]
Hey there, I was jumping in to thank you for the playground, it's useful to test zod schemas from time to time and to give you some suggestions:

1. The interface could be a bit more intuitive, one step forward would be to place an example schema to the elft with an example value to the right.
2. Make sure to link the GitHub repo in the playground. This is because the vercel domain appears to be quite high in google but not the github repo and didn't know where to star it.
3. We could definitely improve the position of the validate button, looks too far. I'm going to push the idea even further implementing keystrokes validation.

**Comment by marilari88** [comment]
hey @giacomocerquone, Your suggestions are welcomed.
1. The interface is indeed raw and lacks intuitiveness. To improve, we could implement an onboarding modal upon initial access, guiding users through the app's features and optionally allowing them to add a zod schema. Futhermore I am not happy with the overall layout, It should be redesigned
2. Totally agree with you. It is easy to do
3. I propose positioning it at the center of the screen to enhance visibility
Hope to have enough time this weekend to go forward with these activities

**Comment by gc-mxm** [comment]
> hey @giacomocerquone, Your suggestions are welcomed.
> 
> 1. The interface is indeed raw and lacks intuitiveness. To improve, we could implement an onboarding modal upon initial access, guiding users through the app's features and optionally allowing them to add a zod schema. Futhermore I am not happy with the overall layout, It should be redesigned
> 2. Totally agree with you. It is easy to do
> 3. I propose positioning it at the center of the screen to enhance visibility
>    Hope to have enough time this weekend to go forward with these activities

1. the onboarding modal is nice, but I can tell you from experience it gets constantly skipped.
3. this is also a good idea, but keep in mind the autovalidation thing I mentioned.

I can help with the activities, of course.

I'm available for implementing whatever the task you want to assign me to 🙂

**Comment by giacomocerquone** [comment]
> hey @giacomocerquone, Your suggestions are welcomed.
> 
> 1. The interface is indeed raw and lacks intuitiveness. To improve, we could implement an onboarding modal upon initial access, guiding users through the app's features and optionally allowing them to add a zod schema. Futhermore I am not happy with the overall layout, It should be redesigned
> 2. Totally agree with you. It is easy to do
> 3. I propose positioning it at the center of the screen to enhance visibility
>    Hope to have enough time this weekend to go forward with these activities

1. The onboarding modal would be nice, but I can tell you from experience it gets constantly skipped. If you still want to add it, just make sure to also let the user start with an example zod schema already written in the editor.
2. this is also a good idea, but keep in mind the autovalidation thing I mentioned.
I can help with the activities, of course.

I'm available for implementing whatever the task you want to assign me to 🙂
