### ISSUE TITLE
Select zod version

### ISSUE THREAD

**Issue by marilari88** [marilari88/zod-playground#15]
It would be useful to add a version picker to the Zod Playground, allowing users to seamlessly switch between different versions of the Zod library. This would enable users to test and learn about the various features and changes introduced in each version, making the playground an even more effective learning and testing tool.

**Comment by giacomocerquone** [comment]
This is interesting but without a server, or an online service that allows lazy loading of NPM modules, it's not feasible IMHO due to the app bundle size that would become huge.

Do you have any idea here?

**Comment by davc0n** [comment]
WIP https://github.com/marilari88/zod-playground/pull/38
