### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by marilari88** [marilari88/zod-playground#17]
Add dark mode and Toggle button to enable it. Save the selected mode to the local storage

**Comment by gc-mxm** [comment]
I'm more used to tailwind or straight css, but it seems like mantine also has an easy way to set dark themes.

Assign me this too

**Comment by giacomocerquone** [comment]
assign me this 🙂

**Comment by giacomocerquone** [comment]
This is taking a bit longer than it should because lots of things needs to be refactored sadly (texts especially)

**Comment by marilari88** [comment]
no problem. Tell me if I can help you in someway

**Comment by SyedFasiuddin** [comment]
any updates?
