### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by giacomocerquone** [marilari88/zod-playground#34]
Sooner or later we'll have to add some tests.
If you have preference over the tool let me know, otherwise for a project like this I'd just spam some e2e tests with playwright

**Comment by marilari88** [comment]
I've thought about it, and I believe that Playwright is a great choice for this kind of project. It is fast and provides support for many browser as well the multitab funcionality (useul for testing share button for example). My only concern is about monaco editor, I hope we manage to test its content
