### ISSUE TITLE
Feedback: Not obvious how to show the parsed value

### ISSUE THREAD

**Issue by IchordeDionysos** [marilari88/zod-playground#35]
Sometimes it's important to remove unexpected fields or to check what the values are after transformations.

To ensure the correct behaviour, being able to see the parsed value would be amazing.

**Comment by IchordeDionysos** [comment]
Okay nevermind, I found how to do it :D 

<img width="263" alt="image" src="https://github.com/marilari88/zod-playground/assets/10195482/e55809a0-b2ff-43a0-9cc9-1342fb5cdef0">

Then maybe take this as a feedback to make it more obvious how to get the parsed data? 🤔

**Comment by marilari88** [comment]
Hey @IchordeDionysos, thank you for your feedback. You can see the parsed data also in the right panel, which you can activate with that button.

![image](https://github.com/marilari88/zod-playground/assets/32909388/7a0b05b0-da62-46b8-b574-afa02f95222f)

However, I agree with you. We should find a more intuitive way to show the parsed data.

**Comment by IchordeDionysos** [comment]
Ahh got it! That's a nice panel.

Maybe we could make the panel by default expanded or change the icon maybe something like:
![1000019956](https://github.com/marilari88/zod-playground/assets/10195482/3c1e836b-f5e3-474b-a9fe-5dcb01501b5d)

Given there are two columns and the icon indicates a two-column icon I thought it was to collapse the value column 🤔
