### ISSUE TITLE
Union custom message is not working 

### ISSUE THREAD

**Issue by kzmsdkn** [marilari88/zod-playground#36]
`const union = z.union([z.number(), z.string()], {required_error: "Missing"});
union.parse(undefined)`

this error doesn't show Missing but Required

**Comment by marilari88** [comment]
Hi @kzmsdkn! I tried the schema and it seems to works fine
https://zod-playground.vercel.app?appdata=N4IgzgxgFgpgtgQxALhALwHQFcB2BLAexwAoBtTHLOAIxgCdiBKAGgAJMwAXOvHAcyYBdNsDowAjljxiAJgH16dAnWSsAOiACyeMGF58NAX0YhmIAG4IANlhhgUpEKZAByWFasEXIQYaA

**Comment by marilari88** [comment]
I consider it closed. @kzmsdkn
