### ISSUE TITLE
checks and tests on CI or pre-commit

### ISSUE THREAD

**Issue by giacomocerquone** [marilari88/zod-playground#58]
So, now that we've added tests and a linter, I'd like to get from you an exhaustive list of the checks we want to run and where to run them.

I'd say the location where we can run them is:

1. client on pre-commit
2. ci

**First question**: do you confirm that the only pipeline we're going to use will be github actions? I've seen also the vercel's integration, do we want to shut that off or we keep it just for the previews (that I can't access btw)?

Based on the location, the available checks are:

On CI: 

- biome:ci

On pre-commit:

- biome:write

Location agnostic:

- playwright

**Second question**: regarding biome, do we want to run it on pre-commit or ci? (consider we can also do both, but the --write option should only be used on client imho, I don't like re-pushing on the repo from the ci).

**Third question**: do you want to run the tests on the production website or on the code the pr changed? Do we want to do both and split the workflows into two, one for the staging app and one for the prs?

**Comment by marilari88** [comment]
hi @giacomocerquone, You did a great job!
1 -  My idea is to change the way we release the application. Basically, I'd like to deliver on tag. To do that we could remove the vercel integration and add a proper github action as https://github.com/marketplace/actions/vercel-action. Alternatively, we could keep the vercel integration bound to a new production branch and push to that branch on tag
2 - We can start lean and add biome check only in the CI (no --write flag of course). @davc0n hates pre-commit and I want to make him happy (waiting for him to change his mind😂)
3- As I understood public repo are not charged and we take advantage of unlimited github actions runs. We can add test check on pr and the main commit
Any other idea is welcome

**Comment by giacomocerquone** [comment]
> hi @giacomocerquone, You did a great job! 1 - My idea is to change the way we release the application. Basically, I'd like to deliver on tag. To do that we could remove the vercel integration and add a proper github action as https://github.com/marketplace/actions/vercel-action. Alternatively, we could keep the vercel integration bound to a new production branch and push to that branch on tag 2 - We can start lean and add biome check only in the CI (no --write flag of course). @davc0n hates pre-commit and I want to make him happy (waiting for him to change his mind😂) 3- As I understood public repo are not charged and we take advantage of unlimited github actions runs. We can add test check on pr and the main commit Any other idea is welcome

1. So whatever you prefer I'd say. Probably it's more work than needed to bring the vercel action in here than setting the vercel pipe to only watch and release the production branch
2. ahaha I hate pre-commits as well but I get there are situations in which it might come in handy
3. very good news
